GET http://localhost:8080/books
accept: application/json

###
GET http://localhost:8080/books/6

###
POST http://localhost:8080/books
content-type: application/json

{
    "title": "Hulk is not green now",
    "author": "Carl",
    "price": 5.6
}

###
PUT http://localhost:8080/books
content-type: application/json

{
    "id": 6,
    "title": "Hulk is not green now",
    "author": "Carl",
    "price": 5.0
}

###
DELETE http://localhost:8080/books/6

###

